### ISSUE TITLE
Parsing AM/PM

### ISSUE THREAD

**Issue by brewin** [erikc5000/island-time#101]
Thanks for this useful library! I'm trying to parse a string with AM/PM, but `amPm()` doesn't seem to have any effect.

```Kotlin
val parser = dateTimeParser {
    year(4)
    +'-'
    monthNumber(2)
    +'-'
    dayOfMonth(2)
    +' '
    hourOfDay(2)
    +':'
    minuteOfHour(2)
    +' '
    amPm()
}

val hour = "2020-07-14 03:56 PM".toDateTime(parser).hour.toString()
println(hour)
```
I expected `hour` to be 15, but it's 3. Is this a bug or am I missing something?

**Comment by erikc5000** [comment]
You probably want to use `clockHourOfAmPm()` instead of `hourOfDay()`.

**Comment by erikc5000** [comment]
Oh wait - that's not in yet. I've been working on a major overhaul to formatting/parsing. There's no field associated with any of the other types of hours beyond the hour of the day. Might be able to add a quick workaround in the next patch release.

**Comment by brewin** [comment]
No problem. I'll just add a workaround to my code for now. I'll just go ahead and close this then since you're working on an overhaul.

**Comment by erikc5000** [comment]
Workaround: instead of using `hourOfDay(2)`, you can use this code to apply a transform to convert the clock-hour-of-am-pm to hour-of-day:

```kotlin
wholeNumber(2) {
    onParsed { value ->
        val hourOfAmPm = value % 12
        fields[DateTimeField.HOUR_OF_DAY] = if (hourOfAmPm == 0) 12 else hourOfAmPm 
    }
}
```

**Comment by brewin** [comment]
Thanks. This does the opposite though, right? I need to convert clock-hour-of-am-pm to hour-of-day based on am-pm-of-day. My ugly workaround is to use different parsers based on whether the string contains "AM" or "PM". The PM parser adds 12 to hour-of-day.

**Comment by erikc5000** [comment]
Bah -- I ripped the code for formatting instead of parsing, so that obviously doesn't work. What you're doing sounds right -- at least until the derived fields are handled better as part of the resolving process.
