### ISSUE TITLE
Issue building for iOS - atomicfu

### ISSUE THREAD

**Issue by liujoshua** [erikc5000/island-time#65]
I have been trying to fix this build error on iOS item and finally narrowed it down to island-time. I added Kotlin atomicfu and made various other attempts to fix it

```
Extracting dependency: /Users/runner/.konan/cache/clang-llvm-apple-8.0.0-darwin-macos.tar.gz into /Users/runner/.konan/dependencies
e: Could not find "atomicfu-cinterop-interop" in [/Users/runner/runners/2.262.1/work/ReimaginedLampMobileApps/ReimaginedLampMobileApps, /Users/runner/.konan/klib, /Users/runner/.konan/kotlin-native-macos-1.3.71/klib/common, /Users/runner/.konan/kotlin-native-macos-1.3.71/klib/platform/ios_x64].
```

Is there a sample project I could look at?

Here is a [branch](https://github.com/liujoshua/KMPDependenciesTest/tree/island-time-only) and [build](https://github.com/liujoshua/KMPDependenciesTest/runs/687818548) for repro 

Thank you for making this library, hope to use it

**Comment by erikc5000** [comment]
Unfortunately, I don't have a sample project at the moment. Adding one to the repo would probably be a good idea though.

As far as the issue itself, nothing stands out at first glance. I'll take a closer look later today.

One thing I might suggest is moving to Gradle 6.x, if possible, since there have been various fixes related to Gradle Metadata, which was also moved out of preview.

**Comment by liujoshua** [comment]
Thanks for the reply! I updated the branch mentioned above to use gradle 6.0.1 and see the same issue. Here's the new run: https://github.com/liujoshua/KMPDependenciesTest/runs/690112034?check_suite_focus=true

**Comment by liujoshua** [comment]
I saw the[ new issue](https://github.com/erikc5000/island-time/issues/66) you created to add sample apps. The repro branch I linked to was a freshly generated Kotlin Native project in IntelliJ 2020.1. If I can fix the build, I'd be happy to start a new project and turn it into a walk through of how to bootstrap a iOS + Android with Island Time

**Comment by erikc5000** [comment]
That would be awesome!

It looks like Island Time's dependency on atomicfu isn't getting published to Maven correctly. I'll try to get that fixed soon and fire off a new release.

In the meantime, you can work around it by adding the dependency manually to commonTest:
```kotlin
       sourceSets["commonTest"].dependencies {
        implementation(kotlin("test-common"))
        implementation(kotlin("test-annotations-common"))

        // Workaround for https://github.com/erikc5000/island-time/issues/65
        implementation("org.jetbrains.kotlinx:atomicfu-common:0.14.2")
    }
```

**Comment by liujoshua** [comment]
Adding atomicfu to commonTest didn't resolve the issue. Thanks for taking a look. I'll check back for a new release in a few days

**Comment by liujoshua** [comment]
Can confirm that upgrading from 0.2.1 to 0.2.2 fixed the issue for me! Thank you
